server:
  port: 80
spring:
  application:
    name: user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  hystrix:
    enabled: true

